### ISSUE TITLE
scripts/bench/run_all.py : module 'urllib' has no attribute 'urlretrieve'

### ISSUE THREAD

**Issue by jamespharvey20** [onqtam/doctest#230]
## Description
`run_all.py` gives me the following error:
````

************** header

== doctest

python ./bench.py compile gcc   --debug --files 200 --tests 0
Traceback (most recent call last):
  File "./bench.py", line 60, in <module>
    urllib.urlretrieve("https://github.com/catchorg/Catch2/releases/download/v" + catch_ver + "/catch.hpp", catch_header)
AttributeError: module 'urllib' has no attribute 'urlretrieve'
Traceback (most recent call last):
  File "./run_all.py", line 48, in <module>
    res = float(runBench(command))
ValueError: could not convert string to float:
````

### Fix

These changes make it run properly:

````
@ line 8
-import urllib
+import urllib.request
@ line 60
-    urllib.urlretrieve("https://github.com/catchorg/Catch2/releases/download/v" + catch_ver + "/catch.hpp", catch_header)
+    urllib.request.urlretrieve("https://github.com/catchorg/Catch2/releases/download/v" + catch_ver + "/catch.hpp", catch_header)
````

I don't know what the proper fix would be to not break it on systems using urllib before `urlretrieve` was moved into `request`.

### Steps to reproduce

`cd scripts/bench && ./run_all.py`

### Extra information

* doctest version: **v2.3.1**
* Operating System: **Arch Linux**
* Compiler+version: **python 3.7.3, and python-urllib3 1.24.2**

**Comment by onqtam** [comment]
I should probably move to python 3.x :)
Thanks for the fix! I'll incorporate it... when I can.
