### ISSUE TITLE
Crash on macOS Release with -fsanitize=address,undefined

### ISSUE THREAD

**Issue by iboB** [onqtam/doctest#317]
## Description

This is a release-only mac-only issue, so I would dub it relatively low priority.

doctest crashes even with the most simple test on mac with `-fsanitize=address,undefined` on this line: https://github.com/onqtam/doctest/blob/master/doctest/parts/doctest.cpp#L3049 (`p->cout = &std::cout;`)

### Steps to reproduce

* A single line simple test case `CHECK(true);`
* Build on mac with `cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined"`
* Run test. Crash on the line from above

Can't be reproduced on anything other than mac and Release.

### Extra information

An example log from the crash

```
==3100==ERROR: AddressSanitizer: unknown-crash on address 0x000104ce4048 at pc 0x000104be6861 bp 0x7ffeeb053b10 sp 0x7ffeeb053b08
READ of size 8 at 0x000104ce4048 thread T0
    #0 0x104be6860 in doctest::Context::run() doctest_impl.h:3049
    #1 0x104bee421 in main doctest_impl.h:3316
    #2 0x7fff69620114 in start (libdyld.dylib:x86_64+0x1114)
Address 0x000104ce4048 is a wild pointer.
SUMMARY: AddressSanitizer: unknown-crash doctest_impl.h:3049 in doctest::Context::run()
Shadow bytes around the buggy address:
  0x10002099c7b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c7c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c7d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c7e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c7f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10002099c800: 00 00 00 00 00 00 00 00 00[00]00 00 00 00 00 00
  0x10002099c810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c820: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c830: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c840: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10002099c850: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3100==ABORTING
```

A travis-ci build can be seen here: https://travis-ci.org/iboB/dynamix/builds/623850241

**Comment by onqtam** [comment]
Gut feeling: this is some buggy asan/ubsan interaction around me taking an address of the global ```std::cout``` object - I doubt that this is a bug in doctest, but I'll take a look in early 2020.

**Comment by ncihnegn** [comment]
Can't reproduce.

**Comment by mitchgrout** [comment]
Presumably not linked with an `asan`-compatible `libc++`. No reprod.
